server:
  port: 8080

spring:
  application:
    name: customer
  # Database config
  datasource:
    password: 'admin'
    url: jdbc:postgresql://localhost:5432/customer
    username: 'admin'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: 'true'
  #Zipking URL
  zipkin:
    base-url: http://localhost:9411
  #Rabbit MQ URL
  rabbitmq:
    addresses: localhost:5672
#Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
