server:
  port: 8082

spring:
  application:
    name: notification
  #Databse config
  datasource:
    password: 'admin'
    url: jdbc:postgresql://localhost:5432/notification
    username: 'admin'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: 'true'
  #Zipking URL
  zipkin:
    base-url: http://localhost:9411
#Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka