server:
  port: 8083

spring:
  application:
    name: api-gateway

  #Zipking URL
  zipkin:
    base-url: http://localhost:9411

  cloud:
    #gateway
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**
