server:
  port: 8083

spring:
  application:
    name: api-gateway

  #Zipking URL
  zipkin:
    base-url: http://zipkin:9411

  cloud:
    #gateway
    gateway:
      routes:
        - id: customer
          uri: lb://customer
          predicates:
            - Path=/api/v1/customers/**

#Eureka config
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
