server:
  port: 8081

spring:
  application:
    name: fraud
  #Database config
  datasource:
    password: 'password'
    url: jdbc:postgresql://postgres:5432/fraud
    username: 'arjit'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: 'validate'
  #Zipking URL
  zipkin:
    base-url: http://zipkin:9411
#Eureka config
eureka:
  client:
    enabled: false