server:
  port: 8761

spring:
  application:
    name: eureka-server
  #Zipking URL
  zipkin:
    base-url: http://localhost:9411
#Eureka config
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false